### PR TITLE
Include UUID in gather data

### PR DESCRIPTION
**Pull request by Womblue**
This PR enables Gather to generate a unique ID for each machine it is used on. This is the same algorithm as is used in the Carbon Client script of the Carbon Leaderboard and so will match the UUIDs generated by that script.

### CODE REVIEW

**Review by VoxSecundus — APPROVED** [review]

**Review by ColonelPanics — CHANGES_REQUESTED** [review]
The UUID **does not match** what the carbon script gets, I think it's due to case issues. 

```
[root@stumaster [Stu VM Master] gather]# cat test_uuid
if [ -f /etc/machine-id ] ; then
    # Combine machine ID and first physical MAC address to create ID
    MACHINEID=$(cat /etc/machine-id) # Generated by systemd or dbus
elif [ -f /var/lib/dbus/machine-id ] ; then
    MACHINEID="$(cat /var/lib/dbus/machine-id)" # Legacy dbus may not use /etc/machine-id
else
    # Use UUID of root partition
    root_mount=$(awk -v mountpoint="/" '$2==mountpoint {print $1}' /proc/mounts)
    MACHINEID="$(lsblk $root_mount -f -o UUID -n)"
fi

FIRSTMAC=$(lshw -c network  2>/dev/null |grep -m 1 'serial:' |sed 's/.*serial: //g;s/://g')
UUID=$(echo "$MACHINEID$FIRSTMAC" |md5sum |awk '{print $1}')

echo "$UUID"
[root@stumaster [Stu VM Master] gather]# bash test_uuid
e1f688f452fb69ccaafa07856cf0b196
[root@stumaster [Stu VM Master] gather]# git branch -v
  dev/better-access 68b6f6c Improve CPU model name data
* dev/include-uuid  778c885 Fix error
  main              677e959 [behind 21] Bump version
[root@stumaster [Stu VM Master] gather]# /opt/flight/bin/ruby bin/gather collect
Beginning data gather...
Gathering physical data...
Gathering logical data...
/usr/bin/ipmitool
Data gathered and written to /root/gather/var/data.yml
[root@stumaster [Stu VM Master] gather]# /opt/flight/bin/ruby bin/gather show |grep uuid
:sysuuid:
:uuid: 7ad4ee35dd84a5d7772eb3d803a50f3c
```

First MAC from script (`lshw`):
```
       serial: d4:ae:52:9b:1c:22
```

First MAC from gather show:
```
:network:
  eno1:
    :mac: D4:AE:52:9B:1C:22
```

**Review by ColonelPanics — APPROVED** [review]
Looks like it works as expected now

**Comment by Womblue** [comment]
Noting for future - although the MAC address in hunter is stored in a different case to what is used in the Carbon Client's UUID generation method, the UUID mismatch was caused because the MAC was not able to be accessed at all, as it is not in the scope of the `logical_data` function.

**Comment by ColonelPanics** [comment]
> Noting for future - although the MAC address in hunter is stored in a different case to what is used in the Carbon Client's UUID generation method, the UUID mismatch was caused because the MAC was not able to be accessed at all, as it is not in the scope of the `logical_data` function.

Seeing as it's a mix of logical & physical information and only relies on existing data for physical, would it not make sense to have moved it to physical?

**Comment by ColonelPanics** [comment]
My thinking being that this block may query disk data and also requires knowledge of the mac address for the first interface so, instead of querying interfaces twice and unnecessarily shelling out again, we can put things in a more appropriate place

**Pull request merged**
